kind: project
metadata:
  name: katacoda
spec:
  functions:
  # main function example
  - url: gen_iris.py
    name: gen-iris
    kind: local
  # function handler + auto_log example
  - url: trainer.py
    name: trainer
    kind: local
    handler: train
